Working with datasets and cleaning it

In [58]:
import numpy as np
import pandas as pd

Load the dataset

In [59]:
df = pd.read_csv('students.csv')
df

   rollno   name           city   age  marks
0     101  Roger     California  20.0   85.0
1     102    Sam            NaN  22.0    NaN
2     103  Peter          Paris   NaN   95.0
3     104   Alex             LA  18.0   91.0
4     105  Alexa  San Fransisco  21.0    NaN
5     106   John            NaN   NaN   88.0

In [60]:
df.isna()

   rollno   name   city    age  marks
0   False  False  False  False  False
1   False  False   True  False   True
2   False  False  False   True  False
3   False  False  False  False  False
4   False  False  False  False   True
5   False  False   True   True  False

In [61]:
df['age'].isna()

0    False
1    False
2     True
3    False
4    False
5     True
Name: age, dtype: bool

Removing NaN values

In [62]:
df.dropna(inplace=True)

In [63]:
df

   rollno   name        city   age  marks
0     101  Roger  California  20.0   85.0
3     104   Alex          LA  18.0   91.0

Replacing the NaN values

In [64]:
df = pd.read_csv('students.csv')
df

   rollno   name           city   age  marks
0     101  Roger     California  20.0   85.0
1     102    Sam            NaN  22.0    NaN
2     103  Peter          Paris   NaN   95.0
3     104   Alex             LA  18.0   91.0
4     105  Alexa  San Fransisco  21.0    NaN
5     106   John            NaN   NaN   88.0

In [65]:
df['marks'].fillna(0,inplace=True)
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_10528\1007058349.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['marks'].fillna(0,inplace=True)

   rollno   name           city   age  marks
0     101  Roger     California  20.0   85.0
1     102    Sam            NaN  22.0    0.0
2     103  Peter          Paris   NaN   95.0
3     104   Alex             LA  18.0   91.0
4     105  Alexa  San Fransisco  21.0    0.0
5     106   John            NaN   NaN   88.0

In [66]:
df['city'].fillna('Not Applicable',inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10528\849813308.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('Not Applicable',inplace=True)

In [67]:
df

   rollno   name            city   age  marks
0     101  Roger      California  20.0   85.0
1     102    Sam  Not Applicable  22.0    0.0
2     103  Peter           Paris   NaN   95.0
3     104   Alex              LA  18.0   91.0
4     105  Alexa   San Fransisco  21.0    0.0
5     106   John  Not Applicable   NaN   88.0

In [68]:
average_age = int(df['age'].mean())
average_age

20

In [69]:
df['age'].fillna(average_age,inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10528\833791459.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(average_age,inplace=True)

In [70]:
df

   rollno   name            city   age  marks
0     101  Roger      California  20.0   85.0
1     102    Sam  Not Applicable  22.0    0.0
2     103  Peter           Paris  20.0   95.0
3     104   Alex              LA  18.0   91.0
4     105  Alexa   San Fransisco  21.0    0.0
5     106   John  Not Applicable  20.0   88.0

In [74]:
df['city'][1]='Mumbai'
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_10528\1900196825.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][1]='Mumbai'
C:\Users\Admin\AppData\Local\Temp\ipykernel_10528\1900196825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][1]='Mumbai'

   rollno   name            city   age  marks
0     101  Roger      California  20.0   85.0
1     102    Sam          Mumbai  22.0    0.0
2     103  Peter           Paris  20.0   95.0
3     104   Alex              LA  18.0   91.0
4     105  Alexa   San Fransisco  21.0    0.0
5     106   John  Not Applicable  20.0   88.0